# Generated by Django 4.2.7 on 2023-11-24 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 9, 58, 17, 159515)),
        ),
    ]
