# Generated by Django 4.2.7 on 2023-11-24 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 10, 14, 43, 217943)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
